# -*- coding: utf-8 -*-
"""red wine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rEJHR1QJDGHZueOmAVLcF6GujSUUf_Wp
"""

from google.colab import files
import pandas as pd
import io

# Upload the red wine CSV
uploaded = files.upload()

# Automatically get whatever filename was uploaded
filename = list(uploaded.keys())[0]

print("Uploaded filename:", filename)

# Read directly from the uploaded file
df = pd.read_csv(io.BytesIO(uploaded[filename]), sep=";")

# Check dataset
print("\nDataset shape:", df.shape)
print("Duplicates:", df.duplicated().sum())
print("Missing values:", df.isnull().sum().sum())

display(df.head())

X = df.drop("quality", axis=1)
y = df["quality"]

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nFeatures:")
print(X.columns.tolist())

print("\nQuality distribution:")
print(y.value_counts().sort_index())

"""Evaluation framework"""

from sklearn.model_selection import RepeatedKFold

# 5-fold cross-validation repeated 3 times
cv = RepeatedKFold(
    n_splits=5,
    n_repeats=3,
    random_state=42
)

print("Total evaluation folds:", cv.get_n_splits())

"""mean-predictor baseline"""

from sklearn.dummy import DummyRegressor
from sklearn.model_selection import cross_validate
from sklearn.metrics import make_scorer
from scipy.stats import spearmanr
import numpy as np

# Spearman correlation scorer
def spearman_score(y_true, y_pred):
    return spearmanr(y_true, y_pred).statistic

scoring = {
    "MAE": "neg_mean_absolute_error",
    "RMSE": "neg_root_mean_squared_error",
    "R2": "r2",
    "Spearman": make_scorer(spearman_score)
}

# Mean-predictor baseline
baseline = DummyRegressor(strategy="mean")

baseline_results = cross_validate(
    baseline,
    X,
    y,
    cv=cv,
    scoring=scoring
)

# Convert negative sklearn error scores to positive errors
mae = -baseline_results["test_MAE"]
rmse = -baseline_results["test_RMSE"]
r2 = baseline_results["test_R2"]
spearman = baseline_results["test_Spearman"]

print("RED WINE — MEAN PREDICTOR BASELINE")
print("----------------------------------")
print(f"MAE:      {mae.mean():.4f} ± {mae.std():.4f}")
print(f"RMSE:     {rmse.mean():.4f} ± {rmse.std():.4f}")
print(f"R²:       {r2.mean():.4f} ± {r2.std():.4f}")
print(f"Spearman: {np.nanmean(spearman):.4f} ± {np.nanstd(spearman):.4f}")

"""StandardScaler → Ridge Regression"""

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV, cross_validate, KFold
from sklearn.metrics import make_scorer
from scipy.stats import spearmanr
import numpy as np

# Pipeline: scaling happens inside CV
ridge_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("ridge", Ridge())
])

# Hyperparameters to test
ridge_params = {
    "ridge__alpha": [0.01, 0.1, 1, 10, 100]
}

# Inner CV: used ONLY for hyperparameter selection
inner_cv = KFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

# Grid search
ridge_search = GridSearchCV(
    estimator=ridge_pipeline,
    param_grid=ridge_params,
    scoring="neg_root_mean_squared_error",
    cv=inner_cv,
    n_jobs=-1
)

# Evaluation metrics
def spearman_score(y_true, y_pred):
    return spearmanr(y_true, y_pred).statistic

scoring = {
    "MAE": "neg_mean_absolute_error",
    "RMSE": "neg_root_mean_squared_error",
    "R2": "r2",
    "Spearman": make_scorer(spearman_score)
}

# Outer CV = the 5-fold × 3-repeat CV we already created
ridge_results = cross_validate(
    ridge_search,
    X,
    y,
    cv=cv,
    scoring=scoring,
    return_estimator=True,
    n_jobs=-1
)

# Convert error scores to positive values
ridge_mae = -ridge_results["test_MAE"]
ridge_rmse = -ridge_results["test_RMSE"]
ridge_r2 = ridge_results["test_R2"]
ridge_spearman = ridge_results["test_Spearman"]

print("RED WINE — RIDGE REGRESSION")
print("--------------------------------")
print(f"MAE:      {ridge_mae.mean():.4f} ± {ridge_mae.std():.4f}")
print(f"RMSE:     {ridge_rmse.mean():.4f} ± {ridge_rmse.std():.4f}")
print(f"R²:       {ridge_r2.mean():.4f} ± {ridge_r2.std():.4f}")
print(f"Spearman: {ridge_spearman.mean():.4f} ± {ridge_spearman.std():.4f}")

print("\nBest alpha selected in each outer fold:")
best_alphas = [
    est.best_params_["ridge__alpha"]
    for est in ridge_results["estimator"]
]
print(best_alphas)

"""Next: Model 2 — KNN Regressor"""

from sklearn.neighbors import KNeighborsRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV, cross_validate

# KNN pipeline
knn_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("knn", KNeighborsRegressor())
])

# Hyperparameters
knn_params = {
    "knn__n_neighbors": [3, 5, 7, 9, 11, 15],
    "knn__weights": ["uniform", "distance"]
}

# Inner tuning
knn_search = GridSearchCV(
    estimator=knn_pipeline,
    param_grid=knn_params,
    scoring="neg_root_mean_squared_error",
    cv=inner_cv,
    n_jobs=-1
)

# Outer evaluation
knn_results = cross_validate(
    knn_search,
    X,
    y,
    cv=cv,
    scoring=scoring,
    return_estimator=True,
    n_jobs=-1
)

# Extract metrics
knn_mae = -knn_results["test_MAE"]
knn_rmse = -knn_results["test_RMSE"]
knn_r2 = knn_results["test_R2"]
knn_spearman = knn_results["test_Spearman"]

print("RED WINE — KNN REGRESSOR")
print("--------------------------------")
print(f"MAE:      {knn_mae.mean():.4f} ± {knn_mae.std():.4f}")
print(f"RMSE:     {knn_rmse.mean():.4f} ± {knn_rmse.std():.4f}")
print(f"R²:       {knn_r2.mean():.4f} ± {knn_r2.std():.4f}")
print(f"Spearman: {knn_spearman.mean():.4f} ± {knn_spearman.std():.4f}")

print("\nBest KNN parameters selected in each outer fold:")

best_knn_params = [
    est.best_params_
    for est in knn_results["estimator"]
]

for i, params in enumerate(best_knn_params, start=1):
    print(f"Fold {i}: {params}")

"""Model 3 — Random Forest Regressor"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV, cross_validate

# Random Forest
rf = RandomForestRegressor(
    random_state=42,
    n_jobs=1
)

# Hyperparameter grid
rf_params = {
    "n_estimators": [100, 200],
    "max_depth": [None, 10, 20],
    "min_samples_leaf": [1, 2]
}

# Inner CV hyperparameter tuning
rf_search = GridSearchCV(
    estimator=rf,
    param_grid=rf_params,
    scoring="neg_root_mean_squared_error",
    cv=inner_cv,
    n_jobs=-1
)

# Outer repeated cross-validation
rf_results = cross_validate(
    rf_search,
    X,
    y,
    cv=cv,
    scoring=scoring,
    return_estimator=True,
    n_jobs=-1
)

# Extract metrics
rf_mae = -rf_results["test_MAE"]
rf_rmse = -rf_results["test_RMSE"]
rf_r2 = rf_results["test_R2"]
rf_spearman = rf_results["test_Spearman"]

print("RED WINE — RANDOM FOREST REGRESSOR")
print("------------------------------------")
print(f"MAE:      {rf_mae.mean():.4f} ± {rf_mae.std():.4f}")
print(f"RMSE:     {rf_rmse.mean():.4f} ± {rf_rmse.std():.4f}")
print(f"R²:       {rf_r2.mean():.4f} ± {rf_r2.std():.4f}")
print(f"Spearman: {rf_spearman.mean():.4f} ± {rf_spearman.std():.4f}")

print("\nBest Random Forest parameters selected in each outer fold:")

best_rf_params = [
    est.best_params_
    for est in rf_results["estimator"]
]

for i, params in enumerate(best_rf_params, start=1):
    print(f"Fold {i}: {params}")

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV, cross_validate

# Random Forest
rf = RandomForestRegressor(
    random_state=42,
    n_jobs=-1
)

# Smaller tuning grid
rf_params = {
    "n_estimators": [100],
    "max_depth": [None, 10],
    "min_samples_leaf": [1, 2]
}

# Inner hyperparameter tuning
rf_search = GridSearchCV(
    estimator=rf,
    param_grid=rf_params,
    scoring="neg_root_mean_squared_error",
    cv=3,                 # 3-fold INNER CV
    n_jobs=1
)

# Outer evaluation:
# keep our required 5-fold × 3 repeats
rf_results = cross_validate(
    rf_search,
    X,
    y,
    cv=cv,
    scoring=scoring,
    return_estimator=True,
    n_jobs=-1
)

# Results
rf_mae = -rf_results["test_MAE"]
rf_rmse = -rf_results["test_RMSE"]
rf_r2 = rf_results["test_R2"]
rf_spearman = rf_results["test_Spearman"]

print("RED WINE — RANDOM FOREST REGRESSOR")
print("------------------------------------")
print(f"MAE:      {rf_mae.mean():.4f} ± {rf_mae.std():.4f}")
print(f"RMSE:     {rf_rmse.mean():.4f} ± {rf_rmse.std():.4f}")
print(f"R²:       {rf_r2.mean():.4f} ± {rf_r2.std():.4f}")
print(f"Spearman: {rf_spearman.mean():.4f} ± {rf_spearman.std():.4f}")

print("\nBest parameters selected in each outer fold:")

for i, est in enumerate(rf_results["estimator"], 1):
    print(f"Fold {i}: {est.best_params_}")

"""Model 4 — SVR"""

from sklearn.svm import SVR
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV, cross_validate

# Scaling is important for SVR
svr_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("svr", SVR(kernel="rbf"))
])

# Small tuning grid
svr_params = {
    "svr__C": [1, 10],
    "svr__epsilon": [0.1, 0.2]
}

# Inner tuning
svr_search = GridSearchCV(
    estimator=svr_pipeline,
    param_grid=svr_params,
    scoring="neg_root_mean_squared_error",
    cv=3,
    n_jobs=-1
)

# Outer evaluation: same 5-fold × 3 repeats
svr_results = cross_validate(
    svr_search,
    X,
    y,
    cv=cv,
    scoring=scoring,
    return_estimator=True,
    n_jobs=-1
)

# Extract metrics
svr_mae = -svr_results["test_MAE"]
svr_rmse = -svr_results["test_RMSE"]
svr_r2 = svr_results["test_R2"]
svr_spearman = svr_results["test_Spearman"]

print("RED WINE — SVR")
print("--------------------------------")
print(f"MAE:      {svr_mae.mean():.4f} ± {svr_mae.std():.4f}")
print(f"RMSE:     {svr_rmse.mean():.4f} ± {svr_rmse.std():.4f}")
print(f"R²:       {svr_r2.mean():.4f} ± {svr_r2.std():.4f}")
print(f"Spearman: {svr_spearman.mean():.4f} ± {svr_spearman.std():.4f}")

print("\nBest SVR parameters selected in each outer fold:")

for i, est in enumerate(svr_results["estimator"], 1):
    print(f"Fold {i}: {est.best_params_}")

import pandas as pd
import numpy as np

n_folds = len(ridge_mae)

red_fold_results = pd.DataFrame({
    "Fold": np.arange(1, n_folds + 1),

    "Ridge_MAE": ridge_mae,
    "Ridge_RMSE": ridge_rmse,
    "Ridge_R2": ridge_r2,
    "Ridge_Spearman": ridge_spearman,

    "KNN_MAE": knn_mae,
    "KNN_RMSE": knn_rmse,
    "KNN_R2": knn_r2,
    "KNN_Spearman": knn_spearman,

    "RF_MAE": rf_mae,
    "RF_RMSE": rf_rmse,
    "RF_R2": rf_r2,
    "RF_Spearman": rf_spearman,

    "SVR_MAE": svr_mae,
    "SVR_RMSE": svr_rmse,
    "SVR_R2": svr_r2,
    "SVR_Spearman": svr_spearman
})

red_fold_results.to_csv(
    "red_wine_fold_results.csv",
    index=False
)

red_fold_results

from scipy.stats import friedmanchisquare

statistic, p_value = friedmanchisquare(
    ridge_rmse,
    knn_rmse,
    rf_rmse,
    svr_rmse
)

print("FRIEDMAN TEST — RED WINE RMSE")
print("--------------------------------")
print(f"Statistic: {statistic:.4f}")
print(f"p-value:   {p_value:.6f}")

if p_value < 0.05:
    print("Result: Significant differences exist among the algorithms.")
else:
    print("Result: No statistically significant difference was detected among the algorithms.")

from scipy.stats import wilcoxon
from itertools import combinations
import pandas as pd

models = {
    "Ridge": ridge_rmse,
    "KNN": knn_rmse,
    "Random Forest": rf_rmse,
    "SVR": svr_rmse
}

pairwise_results = []

# Perform pairwise Wilcoxon tests
for model1, model2 in combinations(models.keys(), 2):

    stat, p = wilcoxon(
        models[model1],
        models[model2],
        alternative="two-sided"
    )

    pairwise_results.append({
        "Model 1": model1,
        "Model 2": model2,
        "Wilcoxon Statistic": stat,
        "Raw p-value": p
    })

pairwise_df = pd.DataFrame(pairwise_results)

# Holm correction
m = len(pairwise_df)

sorted_indices = pairwise_df["Raw p-value"].argsort()
sorted_p = pairwise_df.loc[
    sorted_indices, "Raw p-value"
].values

holm_adjusted = []

for i, p in enumerate(sorted_p):
    adjusted_p = min((m - i) * p, 1.0)
    holm_adjusted.append(adjusted_p)

# Enforce monotonicity
for i in range(1, len(holm_adjusted)):
    holm_adjusted[i] = max(
        holm_adjusted[i],
        holm_adjusted[i-1]
    )

pairwise_df.loc[
    sorted_indices, "Holm Adjusted p-value"
] = holm_adjusted

pairwise_df["Significant (α=0.05)"] = (
    pairwise_df["Holm Adjusted p-value"] < 0.05
)

pairwise_df

"""save"""

pairwise_df.to_csv(
    "red_wine_wilcoxon_posthoc.csv",
    index=False
)

print("Saved successfully.")

"""COST"""

import pandas as pd

cost_results = pd.DataFrame({
    "Model": ["Ridge", "KNN", "Random Forest", "SVR"],

    "Mean Fit Time (s)": [
        ridge_results["fit_time"].mean(),
        knn_results["fit_time"].mean(),
        rf_results["fit_time"].mean(),
        svr_results["fit_time"].mean()
    ],

    "SD Fit Time (s)": [
        ridge_results["fit_time"].std(),
        knn_results["fit_time"].std(),
        rf_results["fit_time"].std(),
        svr_results["fit_time"].std()
    ],

    "Mean Score Time (s)": [
        ridge_results["score_time"].mean(),
        knn_results["score_time"].mean(),
        rf_results["score_time"].mean(),
        svr_results["score_time"].mean()
    ]
})

print("RED WINE — COMPUTATIONAL COST")
display(cost_results)

cost_results.to_csv(
    "red_wine_computational_cost.csv",
    index=False
)

