# -*- coding: utf-8 -*-
"""white wine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P8nDZl2X8UW-7zpP95GvmRjN7rWg4E96
"""

from google.colab import files
import pandas as pd
import io

uploaded = files.upload()

filename = list(uploaded.keys())[0]

white_df = pd.read_csv(
    io.BytesIO(uploaded[filename]),
    sep=";"
)

print("WHITE WINE DATASET")
print("--------------------")
print("File:", filename)
print("Shape:", white_df.shape)
print("Duplicates:", white_df.duplicated().sum())
print("Missing values:", white_df.isnull().sum().sum())

print("\nQuality distribution:")
print(white_df["quality"].value_counts().sort_index())

print("\nColumns:")
print(white_df.columns.tolist())

# Features and target
X_white = white_df.drop("quality", axis=1)
y_white = white_df["quality"]

print("X shape:", X_white.shape)
print("y shape:", y_white.shape)

print("\nFeatures:")
print(X_white.columns.tolist())

from sklearn.model_selection import RepeatedKFold

cv_white = RepeatedKFold(
    n_splits=5,
    n_repeats=3,
    random_state=42
)

print("Total white-wine evaluation folds:",
      cv_white.get_n_splits())

"""Step 2 — Mean predictor baseline"""

from sklearn.dummy import DummyRegressor
from sklearn.model_selection import cross_validate
from sklearn.metrics import make_scorer
from scipy.stats import spearmanr
import numpy as np

def spearman_score(y_true, y_pred):
    result = spearmanr(y_true, y_pred).statistic

    if np.isnan(result):
        return np.nan

    return result

scoring = {
    "MAE": "neg_mean_absolute_error",
    "RMSE": "neg_root_mean_squared_error",
    "R2": "r2",
    "Spearman": make_scorer(spearman_score)
}

baseline_white = DummyRegressor(strategy="mean")

baseline_white_results = cross_validate(
    baseline_white,
    X_white,
    y_white,
    cv=cv_white,
    scoring=scoring,
    n_jobs=-1
)

white_baseline_mae = -baseline_white_results["test_MAE"]
white_baseline_rmse = -baseline_white_results["test_RMSE"]
white_baseline_r2 = baseline_white_results["test_R2"]

print("WHITE WINE — MEAN PREDICTOR BASELINE")
print("--------------------------------------")
print(
    f"MAE:  {white_baseline_mae.mean():.4f} ± "
    f"{white_baseline_mae.std():.4f}"
)
print(
    f"RMSE: {white_baseline_rmse.mean():.4f} ± "
    f"{white_baseline_rmse.std():.4f}"
)
print(
    f"R²:   {white_baseline_r2.mean():.4f} ± "
    f"{white_baseline_r2.std():.4f}"
)

print("Spearman: N/A (constant mean prediction)")

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV, cross_validate, KFold

# Ridge pipeline
ridge_white_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("ridge", Ridge())
])

# Same hyperparameter grid used for red wine
ridge_white_params = {
    "ridge__alpha": [0.01, 0.1, 1, 10, 100]
}

# Inner CV for hyperparameter tuning
inner_cv_white = KFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

ridge_white_search = GridSearchCV(
    estimator=ridge_white_pipeline,
    param_grid=ridge_white_params,
    scoring="neg_root_mean_squared_error",
    cv=inner_cv_white,
    n_jobs=-1
)

# Outer 5-fold × 3 repeated evaluation
ridge_white_results = cross_validate(
    ridge_white_search,
    X_white,
    y_white,
    cv=cv_white,
    scoring=scoring,
    return_estimator=True,
    n_jobs=-1
)

# Extract metrics
white_ridge_mae = -ridge_white_results["test_MAE"]
white_ridge_rmse = -ridge_white_results["test_RMSE"]
white_ridge_r2 = ridge_white_results["test_R2"]
white_ridge_spearman = ridge_white_results["test_Spearman"]

print("WHITE WINE — RIDGE REGRESSION")
print("--------------------------------")
print(f"MAE:      {white_ridge_mae.mean():.4f} ± {white_ridge_mae.std():.4f}")
print(f"RMSE:     {white_ridge_rmse.mean():.4f} ± {white_ridge_rmse.std():.4f}")
print(f"R²:       {white_ridge_r2.mean():.4f} ± {white_ridge_r2.std():.4f}")
print(f"Spearman: {white_ridge_spearman.mean():.4f} ± {white_ridge_spearman.std():.4f}")

print("\nBest alpha selected in each outer fold:")

best_white_ridge_alphas = [
    est.best_params_["ridge__alpha"]
    for est in ridge_white_results["estimator"]
]

print(best_white_ridge_alphas)

"""Next — White Wine KNN"""

from sklearn.neighbors import KNeighborsRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV, cross_validate

knn_white_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("knn", KNeighborsRegressor())
])

# Same search space used for red wine
knn_white_params = {
    "knn__n_neighbors": [3, 5, 7, 9, 11, 15],
    "knn__weights": ["uniform", "distance"]
}

knn_white_search = GridSearchCV(
    estimator=knn_white_pipeline,
    param_grid=knn_white_params,
    scoring="neg_root_mean_squared_error",
    cv=inner_cv_white,
    n_jobs=-1
)

knn_white_results = cross_validate(
    knn_white_search,
    X_white,
    y_white,
    cv=cv_white,
    scoring=scoring,
    return_estimator=True,
    n_jobs=-1
)

white_knn_mae = -knn_white_results["test_MAE"]
white_knn_rmse = -knn_white_results["test_RMSE"]
white_knn_r2 = knn_white_results["test_R2"]
white_knn_spearman = knn_white_results["test_Spearman"]

print("WHITE WINE — KNN REGRESSOR")
print("--------------------------------")
print(f"MAE:      {white_knn_mae.mean():.4f} ± {white_knn_mae.std():.4f}")
print(f"RMSE:     {white_knn_rmse.mean():.4f} ± {white_knn_rmse.std():.4f}")
print(f"R²:       {white_knn_r2.mean():.4f} ± {white_knn_r2.std():.4f}")
print(f"Spearman: {white_knn_spearman.mean():.4f} ± {white_knn_spearman.std():.4f}")

print("\nBest KNN parameters selected in each outer fold:")

for i, est in enumerate(knn_white_results["estimator"], 1):
    print(f"Fold {i}: {est.best_params_}")

"""Next — White Wine Random Forest"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV, cross_validate

rf_white = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

# Reduced tuning grid
rf_white_params = {
    "max_depth": [None, 10],
    "min_samples_leaf": [1, 2]
}

# Small inner CV to keep computation manageable
rf_white_search = GridSearchCV(
    estimator=rf_white,
    param_grid=rf_white_params,
    scoring="neg_root_mean_squared_error",
    cv=2,
    n_jobs=1
)

# Outer evaluation remains 5-fold × 3 repeats
rf_white_results = cross_validate(
    rf_white_search,
    X_white,
    y_white,
    cv=cv_white,
    scoring=scoring,
    return_estimator=True,
    n_jobs=1
)

# Metrics
white_rf_mae = -rf_white_results["test_MAE"]
white_rf_rmse = -rf_white_results["test_RMSE"]
white_rf_r2 = rf_white_results["test_R2"]
white_rf_spearman = rf_white_results["test_Spearman"]

print("WHITE WINE — RANDOM FOREST REGRESSOR")
print("--------------------------------------")
print(f"MAE:      {white_rf_mae.mean():.4f} ± {white_rf_mae.std():.4f}")
print(f"RMSE:     {white_rf_rmse.mean():.4f} ± {white_rf_rmse.std():.4f}")
print(f"R²:       {white_rf_r2.mean():.4f} ± {white_rf_r2.std():.4f}")
print(f"Spearman: {white_rf_spearman.mean():.4f} ± {white_rf_spearman.std():.4f}")

print("\nBest Random Forest parameters selected in each outer fold:")

for i, est in enumerate(rf_white_results["estimator"], 1):
    print(f"Fold {i}: {est.best_params_}")

"""Final white-wine model — SVR"""

from sklearn.svm import SVR
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV, cross_validate

svr_white_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("svr", SVR(kernel="rbf"))
])

svr_white_params = {
    "svr__C": [1, 10],
    "svr__epsilon": [0.1, 0.2]
}

svr_white_search = GridSearchCV(
    estimator=svr_white_pipeline,
    param_grid=svr_white_params,
    scoring="neg_root_mean_squared_error",
    cv=3,
    n_jobs=-1
)

svr_white_results = cross_validate(
    svr_white_search,
    X_white,
    y_white,
    cv=cv_white,
    scoring=scoring,
    return_estimator=True,
    n_jobs=-1
)

white_svr_mae = -svr_white_results["test_MAE"]
white_svr_rmse = -svr_white_results["test_RMSE"]
white_svr_r2 = svr_white_results["test_R2"]
white_svr_spearman = svr_white_results["test_Spearman"]

print("WHITE WINE — SVR")
print("--------------------------------")
print(f"MAE:      {white_svr_mae.mean():.4f} ± {white_svr_mae.std():.4f}")
print(f"RMSE:     {white_svr_rmse.mean():.4f} ± {white_svr_rmse.std():.4f}")
print(f"R²:       {white_svr_r2.mean():.4f} ± {white_svr_r2.std():.4f}")
print(f"Spearman: {white_svr_spearman.mean():.4f} ± {white_svr_spearman.std():.4f}")

print("\nBest SVR parameters selected in each outer fold:")

for i, est in enumerate(svr_white_results["estimator"], 1):
    print(f"Fold {i}: {est.best_params_}")

import pandas as pd
import numpy as np
from scipy.stats import friedmanchisquare, wilcoxon
from itertools import combinations

# ============================================================
# 1. SAVE WHITE-WINE FOLD-LEVEL RESULTS
# ============================================================

white_fold_results = pd.DataFrame({
    "Fold": np.arange(1, len(white_ridge_mae) + 1),

    "Ridge_MAE": white_ridge_mae,
    "Ridge_RMSE": white_ridge_rmse,
    "Ridge_R2": white_ridge_r2,
    "Ridge_Spearman": white_ridge_spearman,

    "KNN_MAE": white_knn_mae,
    "KNN_RMSE": white_knn_rmse,
    "KNN_R2": white_knn_r2,
    "KNN_Spearman": white_knn_spearman,

    "RF_MAE": white_rf_mae,
    "RF_RMSE": white_rf_rmse,
    "RF_R2": white_rf_r2,
    "RF_Spearman": white_rf_spearman,

    "SVR_MAE": white_svr_mae,
    "SVR_RMSE": white_svr_rmse,
    "SVR_R2": white_svr_r2,
    "SVR_Spearman": white_svr_spearman
})

white_fold_results.to_csv(
    "white_wine_fold_results.csv",
    index=False
)

print("WHITE-WINE FOLD RESULTS")
display(white_fold_results)


# ============================================================
# 2. FRIEDMAN TEST ON RMSE
# ============================================================

friedman_stat, friedman_p = friedmanchisquare(
    white_ridge_rmse,
    white_knn_rmse,
    white_rf_rmse,
    white_svr_rmse
)

print("\nFRIEDMAN TEST — WHITE WINE RMSE")
print("--------------------------------")
print(f"Statistic: {friedman_stat:.4f}")
print(f"p-value:   {friedman_p:.6f}")

if friedman_p < 0.05:
    print("Result: Significant differences exist among the algorithms.")
else:
    print("Result: No statistically significant difference was detected.")


# ============================================================
# 3. PAIRWISE WILCOXON TESTS
# ============================================================

models_white = {
    "Ridge": white_ridge_rmse,
    "KNN": white_knn_rmse,
    "Random Forest": white_rf_rmse,
    "SVR": white_svr_rmse
}

pairwise_white = []

for model1, model2 in combinations(models_white.keys(), 2):

    stat, p = wilcoxon(
        models_white[model1],
        models_white[model2],
        alternative="two-sided"
    )

    pairwise_white.append({
        "Model 1": model1,
        "Model 2": model2,
        "Wilcoxon Statistic": stat,
        "Raw p-value": p
    })

white_pairwise_df = pd.DataFrame(pairwise_white)


# ============================================================
# 4. HOLM MULTIPLE-COMPARISON CORRECTION
# ============================================================

m = len(white_pairwise_df)

sorted_indices = white_pairwise_df[
    "Raw p-value"
].argsort()

sorted_p = white_pairwise_df.loc[
    sorted_indices,
    "Raw p-value"
].values

holm_adjusted = []

for i, p in enumerate(sorted_p):
    adjusted_p = min((m - i) * p, 1.0)
    holm_adjusted.append(adjusted_p)

# Ensure monotonic Holm-adjusted p-values
for i in range(1, len(holm_adjusted)):
    holm_adjusted[i] = max(
        holm_adjusted[i],
        holm_adjusted[i - 1]
    )

white_pairwise_df.loc[
    sorted_indices,
    "Holm Adjusted p-value"
] = holm_adjusted

white_pairwise_df["Significant (α=0.05)"] = (
    white_pairwise_df[
        "Holm Adjusted p-value"
    ] < 0.05
)

print("\nWILCOXON POST-HOC TEST — WHITE WINE")
display(white_pairwise_df)

white_pairwise_df.to_csv(
    "white_wine_wilcoxon_posthoc.csv",
    index=False
)


# ============================================================
# 5. COMPUTATIONAL COST
# ============================================================

white_cost_results = pd.DataFrame({
    "Model": [
        "Ridge",
        "KNN",
        "Random Forest",
        "SVR"
    ],

    "Mean Fit Time (s)": [
        ridge_white_results["fit_time"].mean(),
        knn_white_results["fit_time"].mean(),
        rf_white_results["fit_time"].mean(),
        svr_white_results["fit_time"].mean()
    ],

    "SD Fit Time (s)": [
        ridge_white_results["fit_time"].std(),
        knn_white_results["fit_time"].std(),
        rf_white_results["fit_time"].std(),
        svr_white_results["fit_time"].std()
    ],

    "Mean Score Time (s)": [
        ridge_white_results["score_time"].mean(),
        knn_white_results["score_time"].mean(),
        rf_white_results["score_time"].mean(),
        svr_white_results["score_time"].mean()
    ]
})

print("\nWHITE WINE — COMPUTATIONAL COST")
display(white_cost_results)

white_cost_results.to_csv(
    "white_wine_computational_cost.csv",
    index=False
)

print("\nAll white-wine result files saved successfully.")

